"""create location table

Revision ID: 678693144ec5
Revises: 
Create Date: 2019-12-21 12:30:09.162262

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '678693144ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
                    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('type', sa.String(length=10), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('aqi', sa.Integer(), nullable=False),
                    sa.Column('geometric_point', Geometry(
                        geometry_type='POINT', srid=4326), nullable=False),
                    sa.Column('location', postgresql.JSON(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('ref_id', sa.String(length=40), nullable=True),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('ref_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    # ### end Alembic commands ###
