"""create location table

Revision ID: 745a7fc412d9
Revises: 
Create Date: 2019-12-14 23:46:19.719993

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '745a7fc412d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
                    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('type', sa.String(length=10), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('aqi', sa.Integer(), nullable=False),
                    sa.Column('coordinates', Geometry(
                        geometry_type='POINT', srid=4326), nullable=False),
                    sa.Column('ref_id', sa.String(length=40), nullable=True),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
