"""create location table

Revision ID: 882b6df732a6
Revises: 
Create Date: 2019-12-14 23:31:47.140034

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '882b6df732a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
                    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('type', sa.String(length=10), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('aqi', sa.Integer(), nullable=False),
                    sa.Column('coordinates', Geometry(
                        geometry_type='POINT', srid=4326), nullable=False),
                    sa.Column('ref_id', sa.String(length=25), nullable=True),
                    sa.PrimaryKeyConstraint('uuid')
                    )

    # https://github.com/miguelgrinberg/Flask-Migrate/issues/18
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
                    sa.Column('srid', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('auth_name', sa.VARCHAR(length=256),
                              autoincrement=False, nullable=True),
                    sa.Column('auth_srid', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('srtext', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.Column('proj4text', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                                       name='spatial_ref_sys_srid_check'),
                    sa.PrimaryKeyConstraint(
                        'srid', name='spatial_ref_sys_pkey')
                    )
    op.drop_table('location')
    # ### end Alembic commands ###
