"""initialization

Revision ID: 9f771ca28a35
Revises: 
Create Date: 2020-06-18 11:32:59.216135

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f771ca28a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openair_place',
                    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('type', sa.String(length=10), nullable=False),
                    sa.Column('aqi', sa.Integer(), nullable=False),
                    sa.Column('geometric_point', Geometry(geometry_type='POINT',
                                                          srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('location', postgresql.JSON(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('ref_id', sa.String(length=40), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ref_id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_index(op.f('ix_openair_place_created_at'),
                    'openair_place', ['created_at'], unique=False)
    op.create_index(op.f('ix_openair_place_id'),
                    'openair_place', ['id'], unique=False)
    op.create_index(op.f('ix_openair_place_updated_at'),
                    'openair_place', ['updated_at'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
                    sa.Column('srid', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('auth_name', sa.VARCHAR(length=256),
                              autoincrement=False, nullable=True),
                    sa.Column('auth_srid', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('srtext', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.Column('proj4text', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                                       name='spatial_ref_sys_srid_check'),
                    sa.PrimaryKeyConstraint(
                        'srid', name='spatial_ref_sys_pkey')
                    )
    op.drop_index(op.f('ix_openair_place_updated_at'),
                  table_name='openair_place')
    op.drop_index(op.f('ix_openair_place_id'), table_name='openair_place')
    op.drop_index(op.f('ix_openair_place_created_at'),
                  table_name='openair_place')
    op.drop_table('openair_place')
    # ### end Alembic commands ###
